# Generated by Django 3.1.1 on 2020-09-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200920_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
