# Generated by Django 3.1.1 on 2020-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ejoin',
            field=models.CharField(max_length=100),
        ),
    ]
