# Generated by Django 3.1.1 on 2020-09-20 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_employee_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(upload_to='images')),
                ('joined_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
