# Generated by Django 3.1.1 on 2020-09-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_companyhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhead',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
