# Generated by Django 3.1.1 on 2020-09-21 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_companyhead_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='publish',
            new_name='add',
        ),
        migrations.AlterField(
            model_name='employee',
            name='ejoin',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
