# Generated by Django 3.1.1 on 2020-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200921_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ejoin',
            field=models.CharField(max_length=100),
        ),
    ]
