# Generated by Django 3.1.1 on 2020-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200921_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eage',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ejoin',
            field=models.CharField(max_length=100, verbose_name='2020-10-30'),
        ),
    ]
