# Generated by Django 3.1.1 on 2020-09-21 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200921_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ejoin',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
