# Generated by Django 3.1.1 on 2020-09-21 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200921_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhead',
            name='joined_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ejoin',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
