# Generated by Django 3.1.1 on 2020-09-21 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200921_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhead',
            name='joined_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ejoin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
