# Generated by Django 3.1.1 on 2020-09-22 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200921_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(upload_to='images')),
                ('position', models.CharField(max_length=100, null=True)),
                ('joined_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='eage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(),
        ),
    ]
