# Generated by Django 3.1.1 on 2020-09-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_employee_epicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='epicture',
        ),
    ]
